[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_project = "Da5dwAWLN1SuZB5jwPUFmc4Y7n5Movnz77ivTW1JQBNm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://xolana.xen.network"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
